---
title: "Untitled"
author: "Shivam Vats"
date: "2024-03-06"
output: html_document
---

```{r}
options(knitr.table.format = "html", knitr.table.max.rows = 15)
library(viridis)
library(arules)
library(TSP)
library(data.table)
library(ggplot2)
library(Matrix)
library(tcltk)
library(dplyr)
library(devtools)
library(purrr)
library(tidyr)
library(arulesViz)

```

```{r}
# setwd("D:/Text Mining/")
data_csv = read.csv('D:/Text Mining/df2.csv')

#random sample
# data_csv = data_csv %>% sample_n(2000)

#copy of dataframe
df = data_csv

#remove index column
df = df[-c(1)]

# df = df[!names(df) %in% "flight"]


df_pos = df %>%
  filter(label == "pos")

df_neg = df %>%
  filter(label == "neg")

#remove label from the dataframe
df_pos = df_pos[-c(ncol(df_pos))]
df_neg = df_neg[-c(ncol(df_neg))]

#convert into transactions
trans_pos <- as(as.matrix(df_pos), "transactions")
trans_neg <- as(as.matrix(df_neg), "transactions")


#removing transactions having less than 2 items
trans_pos <- trans_pos[rowSums(as(trans_pos, "matrix")) > 1]
trans_neg <- trans_neg[rowSums(as(trans_neg, "matrix")) > 1]


# arules::inspect(trans_pos)
# arules::inspect(trans_neg)
```

```{r}

##### Use apriori to get the RULES
Frules = arules::apriori(trans_pos, parameter = list(support=.45, confidence=.1, minlen=2))
SortedRules <- sort(Frules, by="lift", decreasing=TRUE)
arules::inspect(SortedRules)

```

```{r}
Frules = arules::apriori(trans_neg, parameter = list(support=.5, confidence=.1, minlen=2))
SortedRules <- sort(Frules, by="lift", decreasing=TRUE)
arules::inspect(SortedRules)

```

```{r}

## Plot of which items are most frequent
itemFrequencyPlot(trans, topN=20, type="absolute")

```


```{r}

## Sort rules by a measure such as conf, sup, or lift
SortedRules <- sort(Frules, by="lift", decreasing=TRUE)
arules::inspect(SortedRules[1:15])

```

```{r}

(summary(SortedRules))

```


```{r}

## Selecting or targeting specific rules  RHS
ChocRules <- apriori(data=Foods,parameter = list(supp=.001, conf=.01, minlen=2),
                     appearance = list(default="lhs", rhs="chocloate"),
                     control=list(verbose=FALSE))
ChocRules <- sort(ChocRules, decreasing=TRUE, by="confidence")
inspect(ChocRules[1:4])

```

```{r}

## Selecting rules with LHS specified
CarrotRules <- apriori(data=Foods,parameter = list(supp=.001, conf=.01, minlen=2),
                     appearance = list(default="rhs", lhs="carrot"),
                     control=list(verbose=FALSE))
CarrotRules <- sort(CarrotRules, decreasing=TRUE, by="support")
inspect(CarrotRules[1:4])

```

```{r}

## Visualize
## tcltk

subrules <- head(sort(SortedRules, by="confidence"),10)
plot(subrules)

```


```{r}

plot(subrules, method="graph", engine="htmlwidget")

```
